// Compiled using ts2gas 3.4.4 (TypeScript 3.7.5)

export namespace GBS.KuraGBS{   

        export const CONSTS = {
            CHARS: {
                OPEN: '🔶',
                IN_PROGRESS: '🔵',
                FAILED: '❌',
                CLOSED: '✔️',
                POINT: '🔘',
                FILE: '📁',
                PART: '📙️',
                STAR: '⭐',
                LIGHT: '💡',
                KEEP: '♻️',
                OK: '👌',
                RULE: '📐',
                QUESTION: '❓',
                SEED: '🌱',
                LINK: '🔗',
                ARROW: ' ‣‣ ',
                COACH_FEMALE: '👩🏻‍🦰',
                COACH_MALE: '👦',
                MONEY: '💰',
                TRAFFIC_LIGHT_HORIZONTAL: '🚥',
                TRAFFIC_LIGHT_VERTICAL: '🚦',
                KPI_GREEN: '🟢',
                KPI_RED: '🛑',
                KPI_YELLOW: '⚠️'
            },
            CONFIG: {},
            COLOR: {
                ROW_HIGHLIGHT: "#0078D7",
                ROW_BACKGROUND: "#FFFF00",
                ROW_HIGHLIGHT2: "#E54A19",
                GIAI: '#E0F3FD',
                GIEO: '#97D4F1',
                GIU: '#65C5F1',
                GAT: '#2CB6F5',
                GIAN: '#06589C',
                WHITE: '#FFFFFF'
            },
            MENU: {
                TITLE: "Kura Command",
                INTRO: "Giới thiệu",
                LICENSE: "Bản quyền",
                REGISTRA: "Đăng ký",
                INIT: "Khởi tạo",
                INIT_ID: "ID",
                INIT_ID_SOFT: "ID Phần mềm khác",
                INIT_ID_SHEET: "ID File GSheet",
                INIT_GOOGLE_CALENDAR_ID: "Google Calendar ID",
                INIT_SLACK_HOOK_ID: "Slack ID",
                INIT_SLACK_PROJECT_ID: "Slack Project ID",
                INIT_FILE_OKR: "File OKR & Checklist",
                INIT_FILE_MEASUREMENT: "File Đo lường",
                INIT_FILE_COACHING: "File Coaching",
                INIT_VAR: "Các tham số",
                INIT_GOLDEN_RATIO: '👦 Tỷ lệ vàng (cho bởi coach)',
                WORKBOOK: 'Workbook',
                WB_TOC: "Mục lục (TOC)",
                CAL_COPY: "Copy lịch",
                WB_TOC_CREATE_LINK: "Tạo link điều hướng TOC",
                CAL_COPY_HORIZONTAL: "Copy lịch ngang",
                CAL_COPY_HORIZONTAL_1ROW: "Copy ngang (1 dòng)",
                CAL_COPY_HORIZONTAL_N7ROW: "Copy ngang (n dòng)",
                CAL_COPY_HORIZONTAL_N6ROW: "Copy ngang (n dòng, 6 cột)",
                CAL_COPY_HORIZONTAL_N5ROW: "Copy ngang (n dòng, 5 cột)",
                CAL_COPY_HORIZONTAL_N4ROW: "Copy ngang (n dòng, 4 cột)",
                CAL_COPY_HORIZONTAL_N3ROW: "Copy ngang (n dòng, 3 cột)",
                CAL_COPY_HORIZONTAL_N2ROW: "Copy ngang (n dòng, 2 cột)",
                CAL_COPY_VERTICAL: "Copy lịch dọc",
                CAL_COPY_VERTICAL_30MINS: "Copy dọc 30 phút",
                CAL_COPY_VERTICAL_45MINS: "Copy dọc 45 phút",
                CAL_COPY_VERTICAL_60MINS: "Copy dọc 60 phút",
                CAL_COPY_VERTICAL_75MINS: "Copy dọc 75 phút",
                CAL_COPY_VERTICAL_90MINS: "Copy dọc 90 phút",
                CAL_COPY_VERTICAL_105MINS: "Copy dọc 105 phút",
                CAL_COPY_VERTICAL_120MINS: "Copy dọc 120 phút",
                CAL_COPY_VERTICAL_135MINS: "Copy dọc 135 phút",
                CAL_COPY_VERTICAL_150MINS: "Copy dọc 150 phút",
                CAL_COPY_VERTICAL_165MINS: "Copy dọc 165 phút",
                CAL_COPY_VERTICAL_180MINS: "Copy dọc 180 phút",
                CAL_GCAL: "Lịch Google Calendar",
                CAL_GCAL_OPEN: "Mở Google Calendar",
                CAL_GCAL_EXPORT: "Xuất lịch GCal",
                CAL_GCAL_EXPORT_1WEEK: "Xuất lịch cho tuần này",
                CAL_GCAL_EXPORT_2WEEK: "Xuất lịch cho 2 tuần",
                CAL_GCAL_EXPORT_4WEEK: "Xuất lịch cho 4 tuần",
                CAL_GCAL_EXPORT_13WEEK: "Xuất lịch cho 1 quý (13 tuần)",
                CAL_GCAL_SCHEDULE_AUTO: "Lập lịch xuất tự động (2am)",
                CAL_GCAL_SCHEDULE_AUTO_NOW: "Xuất lịch tự động ngay bây giờ",
                CAL_GCAL_DELETE: "Xóa lịch GCal",
                CAL_GCAL_DELETE_1WEEK: "Xóa lịch tuần này",
                CAL_GCAL_DELETE_2WEEK: "Xóa lịch 2 tuần tới (từ tuần này)",
                CAL_GCAL_DELETE_4WEEK: "Xóa lịch 4 tuần tới (từ tuần này)",
                CAL_GCAL_DELETE_13WEEK: "Xóa lịch 1 quý tới (từ tuần này)",
                CAL_GCAL_DELETE_L1WEEK: "Xóa lịch tuần trước",
                CAL_GCAL_DELETE_L2WEEK: "Xóa lịch 2 tuần trước",
                CAL_GCAL_DELETE_L4WEEK: "Xóa lịch 4 tuần trước",
                CAL_GCAL_DELETE_L13WEEK: "Xóa lịch 1 quý trước (13 tuần)",
                FILE: "File",
                FILE_OPEN: "Mở File",
                FILE_OPEN_OKR: "Mở file OKR & Checklist",
                FILE_OPEN_MEASUREMENT: "Mở file đo lường",
                FILE_OPEN_COACHING: "Mở file coaching",
                ACCEPT_GOOGLE_DRIVE: "Cho phép chỉnh sửa Google Sheets trong Drive của bạn",
                OKR_TITLE: "OKR & Checklist",
                OKR_EDIT: "Hiệu chỉnh",
                OKR_EDIT_CARD: "OKR Card",
                OKR_EDIT_STATE: "Trạng thái",
                MEASURE_TITLE: "Đo Lường",
                MEASURE_EDIT: "Hiệu chỉnh"
            },
            MESSAGE: {
                WELCOME_TITLE: "CHÀO MỪNG",
                WELCOME_TEXT: "CHÀO MỪNG BẠN ĐẾN VỚI KURA DEFAULT DIARY VERSION 4.1 - MỘT CÔNG CỤ PHỤC VỤ CHO CỘNG ĐỒNG VungKiemTien.COM - Điểm Giao Hòa",
                WARN_TITLE: "THÔNG TIN BẢN QUYỀN",
                WARN_TEXT: "CHÚ Ý: TÀI LIỆU NÀY THUỘC BẢN QUYỀN CỦA CÔNG TY KURA\n\nNGHIÊM CẤM MỌI HÀNH VI SAO CHÉP, SỬ DỤNG TRÁI VỚI QUY ĐỊNH & \nTHỎA THUẬN BẢO MẬT CỦA KURA",
                SET_CAL_ID: 'Thiết lập Calendar ID',
                SET_SLACK_HOOK_ID: 'Thiết lập Slack Hook ID',
                CHECKLICH_TITLE: "KIỂM TRA LỊCH ĐÃ LẬP",
                CHECKLICH_TEXT: "Có những phần sau chưa được lập lịch khớp: \n(Ấn Esc để thoát)\n",
                CHECKLICH_OK: "Lịch lập đã khớp với lịch phân bổ. Chúc mừng bạn!",
                MESSAGE_BOX_TITLE: "THÔNG BÁO",
                FILE_DD_WRONG_FILE: "File hiện tại không phải file Defaut Diary",
                GUIDE_OPEN: 'Click vào link để mở ',
                GUIDE_CANNOT_OPEN: 'Không thể mở file do chưa thiết lập hay xảy ra lỗi!',
                LOG: 'Giãn',
                TOP_DOWN_DAY: "Ngày Top-Down",
                BOTTOM_UP_DAY: "Ngày Bottom-Up",
                FLEX_DAY: "Ngày Linh Hoạt",
                REASON_TO_BEILIVE_VN: "Tôi tin tưởng vào sự chọn lựa của tôi bởi vì danh mục hành động của tôi đã đầy đủ và sáng rõ, tầm nhìn của tôi trở nên tập trung & được tích hợp. Trực giác của tôi tinh tế, viễn cảnh rõ nét, các quyết định rõ ràng và tâm lý luôn giữ tĩnh tại, ung dung.",
                TIME_MANAGEMENT_FOCUS_VN: "Ý nghĩa của việc quản lý thời gian là giúp bạn xác định nhiệm vụ quan trọng nhất mình có thể làm vào thời điểm hiện tại, cung cấp cho bạn các công cụ và kỹ thuật để bắt đầu ngay lập tức với nhiệm vụ đó và tiếp tục xử lý nó cho đến khi hoàn thành.",
                START_Q1: 'Đây có phải là việc thuộc Bộ 3 Chủ Chốt trong ngày không?',
                START_Q2: 'Mục tiêu tôi cần đạt được trong khung thời gian này là gì? Đâu là các kết quả then chốt tôi cần đạt được?',
                START_Q3: 'Đâu là 20% yếu tố tạo nên 80% sự thành công của tôi trong khung thời gian này?',
                START_Q3a: 'Nhớ lại lần trước, tôi đang làm tới đâu?',
                START_Q4: 'Nhà Đầu Tư Thiên Thần của tôi trả tôi bao nhiêu giá trị khi làm việc này Đáng và Đúng? Tôi trả Nhà Đầu Tư bao nhiêu tuổi thọ nếu làm Không Đáng và Không Đúng?',
                START_Q5: 'Tôi sử dụng G nào trong 5G để xử lý công việc này?',
                START_Q6: 'Tôi sử dụng T nào trong 5T để xử lý công việc này?',
                START_Q7: 'Mục tiêu này có liên quan như thế nào đến mục tiêu quý của tôi?',
                START_Q8: 'Tôi cần "bắn viên đạn nhỏ" nào trong khung thời gian này?',
                START_Q9: 'Tôi muốn kiểm tra giả thiết nào trong khung thời gian này?',
                START_Q10: 'Việc này có phải là một "hành trình 20 dặm" của tôi không?',
                START_Q11: 'Tôi có thể sử dụng công cụ/nguyên tắc/kỹ thuật/phương pháp/best-practice nào?',
                START_Q12: 'Tôi muốn quan sát và ghi nhận phần nào trong ABCDEHS?',
                END_Q1: 'Cảm giác của tôi hiện tại như thế nào sau khi kết thúc khung thời gian?',
                END_Q2: 'Tôi có đạt được mục tiêu và các kết quả then chốt không? Tôi có thể ăn mừng với chính mình vì điều gì? (Hãy ăn mừng ngay!)',
                END_Q3: 'Tôi có tập trung, cẩn trọng và kiên nhẫn không?',
                END_Q4: 'Tôi có tự tin, vui vẻ và ung dung không?',
                END_Q5: 'Tôi thu hoạch được những dữ liệu gì? Tôi lưu nó ở kho dữ liệu nào?',
                END_Q6: 'Tôi muốn làm react về điều gì? (Hãy làm đi)',
                END_Q7: 'Tôi muốn làm reflection về điều gì? (Hãy làm đi)',
                END_Q8: 'Tôi đã sử dụng tốt/chưa tốt công cụ/nguyên tắc/kỹ thuật/phương pháp/best-practice nào?',
                END_Q9: 'Tôi cần phải ghi nhớ điều gì? Cái gì tôi muốn rà soát lại theo KURA?',
                END_Q10: 'Từ khóa nào tôi cần phải tập trung? Từ khóa nào tôi cần phải học hỏi?',
                END_Q11: 'Điều gì tôi cần phải làm ngay (first steps)?',
                END_Q12: 'Tôi có bổ sung/cải tiến gì cho quy trình làm việc của mình không?',
                END_Q13: 'Động tác thể dục nào tôi có thể tập ngay bây giờ và chỉ trong 2 phút?',
                END_Q14: 'Ai tôi cần/muốn "chăm sóc" ngay bây giờ trong 2 phút?',
                CHECK_IN_RULE: 'Check-in nghiêm túc, đúng luật giúp bạn đánh giá hiệu quả năng lực và sự tập trung. <a href="https://vungkiemtien.com">‣ Xem</a>',
                CHECK_IN_RATIO: 'Tỷ lệ tiền tích lũy:',
                CHECK_OUT_RULE: 'Check-out nghiêm túc, đúng luật giúp bạn đánh giá hiệu quả năng lực và sự tập trung. <a href="https://vungkiemtien.com">‣ Xem</a>',
                CHECK_OUT_RATIO: 'Tỷ lệ tiền tích lũy khi Giãn:'
            },
            PART: {
                PART_PRI: "<b>MỨC ƯU TIÊN</b>",
                PART_DISTRIBUTE: "<b>KHUNG GIỜ NÀY ĐÁNG GIÁ BAO NHIÊU?</b>",
                REASON_TO_BEILIVE: "<b>Khi nào bạn nên tin sự lựa chọn của bạn?</b>",
                TIME_MANAGEMENT_FOCUS: "<b>Ý nghĩa của quản lý thời gian là gì?</b>",
                START_QUESTION: "<b>CÂU HỎI TỰ VẤN ĐỂ KHỞI ĐỘNG: </b><BR><b><i>Trả lời 1-2 câu hỏi tùy theo bạn thấy cần</i></b>",
                END_QUESTION: "<b>CÂU HỎI TỰ VẤN ĐỂ GIÃN:</b> <BR>Trả lời 1-2 câu hỏi tùy theo bạn thấy cần",
                PART_DISTRIBUTED: "<b>BẠN ĐÃ SỬ DỤNG BAO NHIÊU GIÁ TRỊ CUỘC ĐỜI?</b>",
                GOAL_QUARTER: "<b>MỤC TIÊU QUÝ</b>",
                GOAL_ITEM: "<b>MỤC TIÊU KHUNG THỜI GIAN</b>",
                KEY_RESULT: "<b>Kết quả then chốt</b>",
                OKR_CHECKLIST: "<b>DANH MỤC KIỂM TRA</b>",
                NEEDS: "<b>Needs</b>",
                CHECK_IN: "<b>CHECK IN</b>",
                CHECK_OUT: "<b>CHECK OUT & GIÃN</b>"
            },
            PRIORITY: {
                PRI_8020: "<b>Nhóm 80/20 </b>(eXponential Life)",
                PRI_LIFE_PIECE: "<b>Mảnh ghép cuộc đời</b>",
                PRI_BENEFIT: "<b>Lợi ích</b>",
                PRI_5G: "<b>5G</b>",
                PRI_EADOS: "<b>EADOS</b>",
                PRI_EADOS_FUTURE: "<b>EADOS Future</b>",
                TASK_CODE: "#"
            },
            PROPERTIES: {
                PROP_Setup: "SetUpState",
                CALENDAR_ID: 'calID',
                SLACK_HOOK_ID: 'slackWebHookID',
                SLACK_PROJECT_ID: 'slackProjectID',
                TASK_EXPORT_ROW: "taskExportROW",
                TASK_EXPORT_COL: "taskExportCOL",
                TASK_SUM_EXPORT_ROW: "sumExportRow",
                TASK_SUM_EXPORT_COL: "sumExportCol",
                TASK_EXPORT_LIST: "exportList",
                TASK_WEEK_TO_EXPORT: "weekToExport",
                TASK_WEEK_START: "weekStart",
                OKR_FILE_ID: "okrFileID",
                MEASUREMENT_FILE_ID: "measurementFileID",
                COACHING_FILE_ID: "coachingFileID",
                GOLDEN_RATIO: "goldenRatio"
            },
            SHEET: {
                FEATURES: "FEA",
                HISTORY: "HIS",
                INIT: "0aInit",
                TOC: "0bTOC"
            },
            SHEET_RANGE: {
                TOC: "A4:H"
            },
            STATE: {
                TASKS_GOAL: 1
            },
            TIME_DISTRIBUTE: {
                DIS_MINS_TOTAL: "Tổng tuổi thọ 'deal' với Nhà Đầu Tư",
                DIS_MINS_PERTIMES: "Tuổi thọ 'deal' với Nhà Đầu Tư",
                DIS_TIME_VALUE: "Số tiền đầu tư nếu làm ĐÁNG & ĐÚNG",
                DIS_TIME_COACHING: "Số tiền được coach định giá dựa trên thực tế",
                DIS_MONDAY_TIMES: "Thứ 2",
                DIS_TUESDAY_TIMES: "Thứ 3",
                DIS_WEDNESDAY_TIMES: "Thứ 4",
                DIS_THURSDAY_TIMES: "Thứ 5",
                DIS_FRIDAY_TIMES: "Thứ 6",
                DIS_SARTURDAY_TIMES: "Thứ 7",
                DIS_SUNDAY_TIMES: "Chủ nhật",
                DIS_START_DATE: "Ngày bắt đầu",
                DIS_NOW: "Thời điểm đo",
                DIS_INVESTED_TIME: "Tuổi thọ đã đem 'deal'",
                DIS_INVESTED_VALUE: "Tiền đầu tư đã 'deal'",
                DIS_ESLAPSE_TIME: "Tuổi thọ còn lại của bạn",
                DIS_ESLAPSE_VALUE: "Ước tính tổng đầu tư CÒN LẠI",
                DIS_SUB: "<b>Bạn và Nhà Đầu Tư Thiên Thần đã lập 'deal' (kèo) đầu tư vào chính bạn. Hãy xem kết quả đo và tự đánh giá bạn đã thực nhận bao nhiêu đầu tư:</b>"
            },
            VARS: {
                OKR_FILE_ID_CELL: "C14",
                CELL_DD_TEMPLATE_FILE_TYPE: "C6",
                SECOND_TRIGGER: 1,
                EXPORT_COUNT_PER_TIMES: 4,
                CHECKLIST_COMMENT_COUNT: 4,
                CHECK_IN_RATIO: 0.1,
                CHECK_OUT_RATIO: 0.2,
                FLAG_LIGHT_GREEN: 5,
                FLAG_LIGHT_YELLOW: 10,
                FLAG_LIGHT_RED: 10
            }
        }

        

   
}

// export var CONSTS = KuraGBS.CONSTS;